name: periodic_table_app
description: A Flutter app for learning about the Periodic Table.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.0
  sqflite: ^2.0.3
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  charts_flutter: ^0.12.0
  flutter_secure_storage: ^7.0.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/elements.json